### PR TITLE
Remove obsolete references to liquid.conf

### PR DESCRIPTION
**Pull request by andreabonel**
The old Liquid hasn't worked since Dynafed.
Let's just stop looking for it.

### CODE REVIEW

**Comment by LeoComandini** [comment]
> The old Liquid hasn't worked since Dynafed.
> Let's just stop looking for it.

Please add this to the commit message

**Comment by LeoComandini** [comment]
utACK 3432f6042d43ea8e92f9f2b80a3298ce11f1b8b0 with comment

**Comment by andreabonel** [comment]
> > The old Liquid hasn't worked since Dynafed.
> > Let's just stop looking for it.
> 
> Please add this to the commit message

Done ;)

**Comment by LeoComandini** [comment]
utACK 9cc48f74c3b2e37c7cd43dbb59b7dfe9cc0b2245

**Pull request merged**
